apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rust-wtransport-server
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Enable HTTP/3 support (experimental)
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        # Optimize for real-time applications
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        # Increase timeout for WebTransport connections
        run.googleapis.com/timeout: "3600s"
        # Allocate more CPU for real-time processing
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/memory: "512Mi"
    spec:
      containerConcurrency: 1000
      containers:
      - image: gcr.io/PROJECT_ID/rust-wtransport-server
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi 